version: '3.7'

services:
  web:
    build: .
    tty: true
    stdin_open: true
    command: yarn start
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3000:3000
